# -----------------------------
# СЕТИ И ТОМA
# -----------------------------
networks:
  wt-net:
    name: ${NETWORK_NAME:-wt-net}
    driver: bridge

volumes:
  redis-data:
  # локальная инфраструктура (поднимается только при включённом profile)
  postgres-data:

# -----------------------------
# СЕРВИСЫ 
# -----------------------------
services:

  # === EDGE / REVERSE PROXY ===
  nginx-proxy:
    image: ${NGINX_IMAGE}
    restart: always
    ports:
      - "80:80"
      - "${NGINX_WT_PORT_HTTP__WORKER:-81}:${NGINX_WT_PORT_HTTP__WORKER:-81}"
      - "443:443"
    environment:
      # DNS резолвер для FQDN (Dev в Docker: 127.0.0.11; Prod можно задать свой)
      NGINX_RESOLVER: ${NGINX_RESOLVER}

      # домены
      PUBLIC_FQDN__WEB: ${PUBLIC_FQDN__WEB}

      # сертификаты (в этом варианте используем WT‑сертификат для всех трёх серверов)
      NGINX_CERT_WT_CRT: ${NGINX_CERT_WT_CRT}
      NGINX_CERT_WT_KEY: ${NGINX_CERT_WT_KEY}

      # поведение прокси
      NGINX_ENABLE_GZIP: ${NGINX_ENABLE_GZIP}
      NGINX_PROXY_READ_TIMEOUT: ${NGINX_PROXY_READ_TIMEOUT}
      NGINX_PROXY_SEND_TIMEOUT: ${NGINX_PROXY_SEND_TIMEOUT}
      NGINX_PROXY_CONNECT_TIMEOUT: ${NGINX_PROXY_CONNECT_TIMEOUT}
      NGINX_PROXY_BUFFERING: ${NGINX_PROXY_BUFFERING}

      # upstream web (стратегия/keepalive/пассивные HC)
      NGINX_UPSTREAM_STRATEGY__WEB: ${NGINX_UPSTREAM_STRATEGY__WEB}
      NGINX_UPSTREAM_KEEPALIVE__WEB: ${NGINX_UPSTREAM_KEEPALIVE__WEB}
      NGINX_UPSTREAM_KEEPALIVE__WORKER: ${NGINX_UPSTREAM_KEEPALIVE__WORKER}
      NGINX_UPSTREAM_KEEPALIVE__VCLASS: ${NGINX_UPSTREAM_KEEPALIVE__VCLASS}
      NGINX_UPSTREAM_KEEPALIVE__RECORDER: ${NGINX_UPSTREAM_KEEPALIVE__RECORDER}
      NGINX_UPSTREAM_MAX_FAILS: ${NGINX_UPSTREAM_MAX_FAILS}
      NGINX_UPSTREAM_FAIL_TIMEOUT: ${NGINX_UPSTREAM_FAIL_TIMEOUT}

      # HSTS
      NGINX_HSTS_MAX_AGE: ${NGINX_HSTS_MAX_AGE}

      # worker http‑порт/ограничение
      NGINX_WT_PORT_HTTP__WORKER: ${NGINX_WT_PORT_HTTP__WORKER}

      # цели upstream'ов
      UPSTREAM_HOST_NAME__WEB_1: ${UPSTREAM_HOST_NAME__WEB_1}
      UPSTREAM_HOST_PORT__WEB_1: ${UPSTREAM_HOST_PORT__WEB_1}
      UPSTREAM_HOST_NAME__WEB_2: ${UPSTREAM_HOST_NAME__WEB_2}
      UPSTREAM_HOST_PORT__WEB_2: ${UPSTREAM_HOST_PORT__WEB_2}
      UPSTREAM_HOST_NAME__WORKER: ${UPSTREAM_HOST_NAME__WORKER}
      UPSTREAM_HOST_PORT__WORKER: ${UPSTREAM_HOST_PORT__WORKER}
    volumes:
      # шаблоны
      - ./nginx-proxy/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      # скрипт рендеринга — попадёт в /docker-entrypoint.d/ и выполнится автоматически
      - ./nginx-proxy/init-nginx.sh:/docker-entrypoint.d/50-init-nginx.sh:ro
      # сертификаты
      - ${WT_CERTS_DIR}:/etc/nginx/certs:ro
    depends_on:
      web-backend-1:
        condition: service_started
      web-backend-2:
        condition: service_started
      worker-backend:
        condition: service_started
    networks: [wt-net]

  # === REDIS (кэш/очереди WT) ===
  redis:
    image: ${REDIS_IMAGE}
    restart: always
    environment:
      REDIS_PASSWORD: ${PASSWORD__REDIS}
    volumes:
      - redis-data:/data
    command: ["redis-server","--appendonly","yes","--requirepass","${PASSWORD__REDIS}"]
    healthcheck:
      test: ["CMD","redis-cli","-a","${PASSWORD__REDIS}","PING"]
      interval: ${HC_INTERVAL__REDIS:-5s}
      timeout: ${HC_TIMEOUT__REDIS:-3s}
      retries: ${HC_RETRIES__REDIS:-5}
    networks: [wt-net]

  # === WEB НОДА №1 ===
  web-backend-1:
    image: ${WT_IMAGE}
    hostname: wt_dev
    platform: linux/amd64
    restart: always
    command: ["/bin/sh","-lc","/WebsoftServer/wait-pg.sh && /WebsoftServer/init-spxml.sh && exec /WebsoftServer/xhttp.out"]
    environment:
      NodesPoolId: "1"
      ExternalDeployment: "true"
      MEMORY_MIMALLOC: "2"
      RoleType: "0"
      # PG WAIT
      PG_WAIT_ENABLED: ${PG_WAIT_ENABLED}
      PG_WAIT_DEADLINE: ${PG_WAIT_DEADLINE}
      PG_WAIT_INTERVAL: ${PG_WAIT_INTERVAL}
      PG_WAIT_ON_TIMEOUT: ${PG_WAIT_ON_TIMEOUT}
      # ====== SPXML (WEB) — роли/кластер/кэш/ComplexHosting ======
      SPXML_CONF_SESSION_EXPIRATION:              ${SPXML_CONF_SESSION_EXPIRATION__WEB}
      SPXML_CONF_MAX_SESSIONS_COUNT:              ${SPXML_CONF_MAX_SESSIONS_COUNT__WEB}
      SPXML_CONF_MAX_FT_DOCS:                     ${SPXML_CONF_MAX_FT_DOCS__WEB}
      SPXML_CONF_UPGRADE_LOCKED:                  ${SPXML_CONF_UPGRADE_LOCKED__WEB}
      SPXML_CONF_IN_PLACE_UPGRADE:                ${SPXML_CONF_IN_PLACE_UPGRADE__WEB}
      SPXML_CONF_REDIS_LIMIT_MEMORY_PERCENTAGE:   ${SPXML_CONF_REDIS_LIMIT_MEMORY_PERCENTAGE__WEB}
      SPXML_CONF_REDIS_LIMIT_MEMORY_MEGABYTES:    ${SPXML_CONF_REDIS_LIMIT_MEMORY_MEGABYTES__WEB}
      SPXML_CONF_LOCAL_OBJECT_CLIENT_CACHE:       ${SPXML_CONF_LOCAL_OBJECT_CLIENT_CACHE__WEB}
      SPXML_CONF_LOCAL_OBJECT_CACHE:              ${SPXML_CONF_LOCAL_OBJECT_CACHE__WEB}
      SPXML_CONF_LOCAL_FILE_CACHE:                ${SPXML_CONF_LOCAL_FILE_CACHE__WEB}
      SPXML_CONF_LUCENE_FT_CACHE:                 ${SPXML_CONF_LUCENE_FT_CACHE__WEB}
      SPXML_CONF_LUCENE_FT_INDEX_RAM_BUFFER_SIZE: ${SPXML_CONF_LUCENE_FT_INDEX_RAM_BUFFER_SIZE__WEB}

      SPXML_CONF_STRICT_WEBROLE:                  ${SPXML_CONF_STRICT_WEBROLE__WEB}
      SPXML_CONF_STRICT_WORKERROLE:               ${SPXML_CONF_STRICT_WORKERROLE__WEB}
      SPXML_CONF_STRICT_ROLE_TYPES:               ${SPXML_CONF_STRICT_ROLE_TYPES__WEB}
      SPXML_CONF_REDIS_MAXMEMORY_ITEM_BYTES:      ${SPXML_CONF_REDIS_MAXMEMORY_ITEM_BYTES}

      SPXML_CONF_COMPLEX_HOSTING_BLOCK:           ${SPXML_CONF_COMPLEX_HOSTING_BLOCK__WEB}

      # ====== Подстановки для шаблона SPXML: БД и Redis (нужны и на WEB) ======
      HOST_NAME__PG:                              ${HOST_NAME__PG}
      HOST_PORT__PG:                              ${HOST_PORT__PG}
      DB_NAME__PG:                                ${DB_NAME__PG}
      DB_USER__PG:                                ${DB_USER__PG}
      DB_PASSWORD__PG:                            ${DB_PASSWORD__PG}

      HOST_NAME__REDIS:                           ${HOST_NAME__REDIS}
      HOST_PORT__REDIS:                           ${HOST_PORT__REDIS}
      PASSWORD__REDIS:                            ${PASSWORD__REDIS}
      OPTS__REDIS:                                ${OPTS__REDIS}
      # ====== для OmniCode ======
      WebTutorServerDir: ${WEBTUTOR_SERVER_DIR}
      DebugWebTutorServerDir: ${DEBUG_WEBTUTOR_SERVER_DIR}
      DefaultNetCoreTargetFramework: ${DEFAULT_NETCORE_TARGET_FRAMEWORK}
      DefaultNetStandardTargetFramework: ${DEFAULT_NETSTANDARD_TARGET_FRAMEWORK}
      WEBSOFT_MSBUILD_SDK_PATH: ${WEBSOFT_MSBUILD_SDK_PATH}
    volumes:
      # Конфиги WebSoft
      - ./websoft/configs/common/license.xfpx:/WebsoftServer/license.xfpx:ro
      - ./websoft/configs/common/resource_sec.json:/WebsoftServer/resource_sec.json
      - ./websoft/configs/common/xHttp.ini:/WebsoftServer/xHttp.ini
      - ./websoft/configs/web-backend/xhttp_config.json:/WebsoftServer/xhttp_config.json
      # шаблоны и скрипты инициализации конфигов
      - ./websoft/configs/common/spxml_unibridge_config.xml.template:/WebsoftServer/configs/spxml_unibridge_config.xml.template:ro
      - ./websoft/configs/common/init-spxml.sh:/WebsoftServer/init-spxml.sh:ro
      - ./websoft/configs/common/wait-pg.sh:/WebsoftServer/wait-pg.sh:ro
      # Рантайм каталоги
      - ./websoft/ft-idx:/WebsoftServer/ft-idx
      - ./websoft/wt_data:/WebsoftServer/wt_data
      - ./websoft/web/webtutor:/WebsoftServer/wt/web/webtutor
      - ./websoft/components:/WebsoftServer/components
      - ./websoft/runtimes/web-backend/platform:/WebsoftServer/platform.runtime
      - ./websoft/runtimes/web-backend/components:/WebsoftServer/components.runtime
      # Логи 
      - ./websoft/Logs/web-backend-1:/WebsoftServer/Logs
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL","wget -q --spider http://localhost:8011/spxml_web/main.htm || exit 1"]
      interval: ${HC_INTERVAL__WEB:-10s}
      timeout: ${HC_TIMEOUT__WEB:-5s}
      start_period: ${HC_START_PERIOD__WEB:-90s}
      retries: ${HC_RETRIES__WEB:-12}
    networks: [wt-net]

  # === WEB НОДА №2 ===
  web-backend-2:
    image: ${WT_IMAGE}
    hostname: wt_dev
    platform: linux/amd64
    restart: always
    command: ["/bin/sh","-lc","/WebsoftServer/wait-pg.sh && /WebsoftServer/init-spxml.sh && exec /WebsoftServer/xhttp.out"]
    environment:
      NodesPoolId: "1"
      ExternalDeployment: "true"
      MEMORY_MIMALLOC: "2"
      RoleType: "0"
      # PG WAIT
      PG_WAIT_ENABLED: ${PG_WAIT_ENABLED}
      PG_WAIT_DEADLINE: ${PG_WAIT_DEADLINE}
      PG_WAIT_INTERVAL: ${PG_WAIT_INTERVAL}
      PG_WAIT_ON_TIMEOUT: ${PG_WAIT_ON_TIMEOUT}
      # ====== SPXML (WEB) — роли/кластер/кэш/ComplexHosting ======
      SPXML_CONF_SESSION_EXPIRATION:              ${SPXML_CONF_SESSION_EXPIRATION__WEB}
      SPXML_CONF_MAX_SESSIONS_COUNT:              ${SPXML_CONF_MAX_SESSIONS_COUNT__WEB}
      SPXML_CONF_MAX_FT_DOCS:                     ${SPXML_CONF_MAX_FT_DOCS__WEB}
      SPXML_CONF_UPGRADE_LOCKED:                  ${SPXML_CONF_UPGRADE_LOCKED__WEB}
      SPXML_CONF_IN_PLACE_UPGRADE:                ${SPXML_CONF_IN_PLACE_UPGRADE__WEB}
      SPXML_CONF_REDIS_LIMIT_MEMORY_PERCENTAGE:   ${SPXML_CONF_REDIS_LIMIT_MEMORY_PERCENTAGE__WEB}
      SPXML_CONF_REDIS_LIMIT_MEMORY_MEGABYTES:    ${SPXML_CONF_REDIS_LIMIT_MEMORY_MEGABYTES__WEB}
      SPXML_CONF_LOCAL_OBJECT_CLIENT_CACHE:       ${SPXML_CONF_LOCAL_OBJECT_CLIENT_CACHE__WEB}
      SPXML_CONF_LOCAL_OBJECT_CACHE:              ${SPXML_CONF_LOCAL_OBJECT_CACHE__WEB}
      SPXML_CONF_LOCAL_FILE_CACHE:                ${SPXML_CONF_LOCAL_FILE_CACHE__WEB}
      SPXML_CONF_LUCENE_FT_CACHE:                 ${SPXML_CONF_LUCENE_FT_CACHE__WEB}
      SPXML_CONF_LUCENE_FT_INDEX_RAM_BUFFER_SIZE: ${SPXML_CONF_LUCENE_FT_INDEX_RAM_BUFFER_SIZE__WEB}

      SPXML_CONF_STRICT_WEBROLE:                  ${SPXML_CONF_STRICT_WEBROLE__WEB}
      SPXML_CONF_STRICT_WORKERROLE:               ${SPXML_CONF_STRICT_WORKERROLE__WEB}
      SPXML_CONF_STRICT_ROLE_TYPES:               ${SPXML_CONF_STRICT_ROLE_TYPES__WEB}
      SPXML_CONF_REDIS_MAXMEMORY_ITEM_BYTES:      ${SPXML_CONF_REDIS_MAXMEMORY_ITEM_BYTES}

      SPXML_CONF_COMPLEX_HOSTING_BLOCK:           ${SPXML_CONF_COMPLEX_HOSTING_BLOCK__WEB}

      # ====== Подстановки для шаблона SPXML: БД и Redis (нужны и на WEB) ======
      HOST_NAME__PG:                              ${HOST_NAME__PG}
      HOST_PORT__PG:                              ${HOST_PORT__PG}
      DB_NAME__PG:                                ${DB_NAME__PG}
      DB_USER__PG:                                ${DB_USER__PG}
      DB_PASSWORD__PG:                            ${DB_PASSWORD__PG}

      HOST_NAME__REDIS:                           ${HOST_NAME__REDIS}
      HOST_PORT__REDIS:                           ${HOST_PORT__REDIS}
      PASSWORD__REDIS:                            ${PASSWORD__REDIS}
      OPTS__REDIS:                                ${OPTS__REDIS}
      # ====== для OmniCode ======
      WebTutorServerDir: ${WEBTUTOR_SERVER_DIR}
      DebugWebTutorServerDir: ${DEBUG_WEBTUTOR_SERVER_DIR}
      DefaultNetCoreTargetFramework: ${DEFAULT_NETCORE_TARGET_FRAMEWORK}
      DefaultNetStandardTargetFramework: ${DEFAULT_NETSTANDARD_TARGET_FRAMEWORK}
      WEBSOFT_MSBUILD_SDK_PATH: ${WEBSOFT_MSBUILD_SDK_PATH}
    volumes:
      # Конфиги WebSoft
      - ./websoft/configs/common/license.xfpx:/WebsoftServer/license.xfpx:ro
      - ./websoft/configs/common/resource_sec.json:/WebsoftServer/resource_sec.json
      - ./websoft/configs/common/xHttp.ini:/WebsoftServer/xHttp.ini
      - ./websoft/configs/web-backend/xhttp_config.json:/WebsoftServer/xhttp_config.json
      # шаблоны и скрипты инициализации конфигов
      - ./websoft/configs/common/spxml_unibridge_config.xml.template:/WebsoftServer/configs/spxml_unibridge_config.xml.template:ro
      - ./websoft/configs/common/init-spxml.sh:/WebsoftServer/init-spxml.sh:ro
      - ./websoft/configs/common/wait-pg.sh:/WebsoftServer/wait-pg.sh:ro
      # Рантайм каталоги
      - ./websoft/ft-idx:/WebsoftServer/ft-idx
      - ./websoft/wt_data:/WebsoftServer/wt_data
      - ./websoft/web/webtutor:/WebsoftServer/wt/web/webtutor
      - ./websoft/components:/WebsoftServer/components
      - ./websoft/runtimes/web-backend/platform:/WebsoftServer/platform.runtime
      - ./websoft/runtimes/web-backend/components:/WebsoftServer/components.runtime
      # Логи 
      - ./websoft/Logs/web-backend-2:/WebsoftServer/Logs
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL","wget -q --spider http://localhost:8011/spxml_web/main.htm || exit 1"]
      interval: ${HC_INTERVAL__WEB:-10s}
      timeout: ${HC_TIMEOUT__WEB:-5s}
      start_period: ${HC_START_PERIOD__WEB:-90s}
      retries: ${HC_RETRIES__WEB:-12}
    networks: [wt-net]
  
  # === WORKER НОДА ===
  worker-backend:
    image: ${WT_IMAGE}
    hostname: wt_dev
    platform: linux/amd64
    restart: always
    command: ["/bin/sh","-lc","/WebsoftServer/wait-pg.sh && /WebsoftServer/init-spxml.sh && exec /WebsoftServer/xhttp.out"]
    environment:
      NodesPoolId: "3"
      ExternalDeployment: "true"
      MEMORY_MIMALLOC: "2"
      RoleType: "1"
      # PG WAIT
      PG_WAIT_ENABLED: ${PG_WAIT_ENABLED}
      PG_WAIT_DEADLINE: ${PG_WAIT_DEADLINE}
      PG_WAIT_INTERVAL: ${PG_WAIT_INTERVAL}
      PG_WAIT_ON_TIMEOUT: ${PG_WAIT_ON_TIMEOUT}
      # ====== SPXML (WORKER) — роли/кластер/кэш/ComplexHosting ======
      SPXML_CONF_SESSION_EXPIRATION:              ${SPXML_CONF_SESSION_EXPIRATION__WORKER}
      SPXML_CONF_MAX_SESSIONS_COUNT:              ${SPXML_CONF_MAX_SESSIONS_COUNT__WORKER}
      SPXML_CONF_MAX_FT_DOCS:                     ${SPXML_CONF_MAX_FT_DOCS__WORKER}
      SPXML_CONF_UPGRADE_LOCKED:                  ${SPXML_CONF_UPGRADE_LOCKED__WORKER}
      SPXML_CONF_IN_PLACE_UPGRADE:                ${SPXML_CONF_IN_PLACE_UPGRADE__WORKER}
      SPXML_CONF_REDIS_LIMIT_MEMORY_PERCENTAGE:   ${SPXML_CONF_REDIS_LIMIT_MEMORY_PERCENTAGE__WORKER}
      SPXML_CONF_REDIS_LIMIT_MEMORY_MEGABYTES:    ${SPXML_CONF_REDIS_LIMIT_MEMORY_MEGABYTES__WORKER}
      SPXML_CONF_LOCAL_OBJECT_CLIENT_CACHE:       ${SPXML_CONF_LOCAL_OBJECT_CLIENT_CACHE__WORKER}
      SPXML_CONF_LOCAL_OBJECT_CACHE:              ${SPXML_CONF_LOCAL_OBJECT_CACHE__WORKER}
      SPXML_CONF_LOCAL_FILE_CACHE:                ${SPXML_CONF_LOCAL_FILE_CACHE__WORKER}
      SPXML_CONF_LUCENE_FT_CACHE:                 ${SPXML_CONF_LUCENE_FT_CACHE__WORKER}
      SPXML_CONF_LUCENE_FT_INDEX_RAM_BUFFER_SIZE: ${SPXML_CONF_LUCENE_FT_INDEX_RAM_BUFFER_SIZE__WORKER}

      SPXML_CONF_STRICT_WEBROLE:                  ${SPXML_CONF_STRICT_WEBROLE__WORKER}
      SPXML_CONF_STRICT_WORKERROLE:               ${SPXML_CONF_STRICT_WORKERROLE__WORKER}
      SPXML_CONF_STRICT_ROLE_TYPES:               ${SPXML_CONF_STRICT_ROLE_TYPES__WORKER}
      SPXML_CONF_REDIS_MAXMEMORY_ITEM_BYTES:      ${SPXML_CONF_REDIS_MAXMEMORY_ITEM_BYTES}

      SPXML_CONF_COMPLEX_HOSTING_BLOCK:           ${SPXML_CONF_COMPLEX_HOSTING_BLOCK__WORKER}

      # ====== Подстановки для шаблона SPXML: БД и Redis (нужны и на WEB) ======
      HOST_NAME__PG:                              ${HOST_NAME__PG}
      HOST_PORT__PG:                              ${HOST_PORT__PG}
      DB_NAME__PG:                                ${DB_NAME__PG}
      DB_USER__PG:                                ${DB_USER__PG}
      DB_PASSWORD__PG:                            ${DB_PASSWORD__PG}

      HOST_NAME__REDIS:                           ${HOST_NAME__REDIS}
      HOST_PORT__REDIS:                           ${HOST_PORT__REDIS}
      PASSWORD__REDIS:                            ${PASSWORD__REDIS}
      OPTS__REDIS:                                ${OPTS__REDIS}
      # ====== для OmniCode ======
      WebTutorServerDir: ${WEBTUTOR_SERVER_DIR}
      DebugWebTutorServerDir: ${DEBUG_WEBTUTOR_SERVER_DIR}
      DefaultNetCoreTargetFramework: ${DEFAULT_NETCORE_TARGET_FRAMEWORK}
      DefaultNetStandardTargetFramework: ${DEFAULT_NETSTANDARD_TARGET_FRAMEWORK}
      WEBSOFT_MSBUILD_SDK_PATH: ${WEBSOFT_MSBUILD_SDK_PATH}
    volumes:
      # Конфиги WebSoft
      - ./websoft/configs/common/license.xfpx:/WebsoftServer/license.xfpx:ro
      - ./websoft/configs/common/resource_sec.json:/WebsoftServer/resource_sec.json
      - ./websoft/configs/common/xHttp.ini:/WebsoftServer/xHttp.ini
      - ./websoft/configs/worker-backend/xhttp_config.json:/WebsoftServer/xhttp_config.json
      # шаблоны и скрипты инициализации конфигов
      - ./websoft/configs/common/spxml_unibridge_config.xml.template:/WebsoftServer/configs/spxml_unibridge_config.xml.template:ro
      - ./websoft/configs/common/init-spxml.sh:/WebsoftServer/init-spxml.sh:ro
      - ./websoft/configs/common/wait-pg.sh:/WebsoftServer/wait-pg.sh:ro
      # Рантайм каталоги
      - ./websoft/ft-idx:/WebsoftServer/ft-idx
      - ./websoft/wt_data:/WebsoftServer/wt_data
      - ./websoft/web/webtutor:/WebsoftServer/wt/web/webtutor
      - ./websoft/components:/WebsoftServer/components
      - ./websoft/runtimes/worker-backend/platform:/WebsoftServer/platform.runtime
      - ./websoft/runtimes/worker-backend/components:/WebsoftServer/components.runtime
      # Логи 
      - ./websoft/Logs/worker-backend:/WebsoftServer/Logs
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL","wget -q --spider http://localhost:8011/spxml_web/main.htm || exit 1"]
      interval: ${HC_INTERVAL__WORKER:-10s}
      timeout: ${HC_TIMEOUT__WORKER:-5s}
      start_period: ${HC_START_PERIOD__WORKER:-90s}
      retries: ${HC_RETRIES__WORKER:-12}
    networks: [wt-net]

  # ====================================================
  # ОПЦИОНАЛЬНАЯ ЛОКАЛЬНАЯ ИНФРА (для Dev) ЧЕРЕЗ PROFILE
  # ====================================================

  postgres:
    profiles: ["local-postgres"]
    image: ${POSTGRES_IMAGE}
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER__PG}
      POSTGRES_PASSWORD: ${DB_PASSWORD__PG}
      POSTGRES_DB: ${DB_NAME__PG}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER__PG} -d ${DB_NAME__PG} -h localhost"]
      interval: ${HC_INTERVAL__PG:-5s}
      timeout: ${HC_TIMEOUT__PG:-10s}
      retries: ${HC_RETRIES__PG:-10}
    networks: [wt-net]